
package com.amateam.crud;

import java.awt.Color;
import javax.swing.JCheckBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Admin
 */
public class Form extends javax.swing.JFrame {

    boolean isForUpdate = false;
    String _id;
    
    /** Creates new form Form */
    public Form() {
        initComponents();
        setLocationRelativeTo(null);
        ButtonSubmit.setText("Save");
    }
    
    public Form(String _id, boolean isForUpdate) {
        this.isForUpdate = isForUpdate;
        this._id = _id;
        
        initComponents();
        setLocationRelativeTo(null);
        ButtonSubmit.setText("Update");
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonGroupGender = new javax.swing.ButtonGroup();
        MainPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LabelName = new javax.swing.JLabel();
        TextFieldFirstName = new javax.swing.JTextField();
        LabelFirstName = new javax.swing.JLabel();
        TextFieldMiddleName = new javax.swing.JTextField();
        LabelMiddleName = new javax.swing.JLabel();
        TextFieldLastName = new javax.swing.JTextField();
        LabelLastName = new javax.swing.JLabel();
        LabelBirthDate = new javax.swing.JLabel();
        ComboBoxDay = new javax.swing.JComboBox<>();
        ComboBoxMonth = new javax.swing.JComboBox<>();
        ComboBoxYear = new javax.swing.JComboBox<>();
        LabelYear = new javax.swing.JLabel();
        LabelMonth = new javax.swing.JLabel();
        LabelDay = new javax.swing.JLabel();
        LabelGender = new javax.swing.JLabel();
        RadioButtonMale = new javax.swing.JRadioButton();
        RadioButtonFemale = new javax.swing.JRadioButton();
        LabelGender1 = new javax.swing.JLabel();
        TextFieldContactNumber = new javax.swing.JTextField();
        LabelContactNumber = new javax.swing.JLabel();
        TextFieldEmailAddress = new javax.swing.JTextField();
        LabelEmailAddress = new javax.swing.JLabel();
        LabelGender2 = new javax.swing.JLabel();
        TextFieldStreetAddress = new javax.swing.JTextField();
        LabelStreetAddress = new javax.swing.JLabel();
        LabelBarangay = new javax.swing.JLabel();
        TextFieldBarangay = new javax.swing.JTextField();
        TextFieldCity = new javax.swing.JTextField();
        TextFieldProvince = new javax.swing.JTextField();
        LabelProvince = new javax.swing.JLabel();
        LabelCity = new javax.swing.JLabel();
        TextFieldZipCode = new javax.swing.JTextField();
        LabelZipCode = new javax.swing.JLabel();
        LabelCoursePreference = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        ButtonSubmit = new javax.swing.JButton();
        LabelCoursePreferenceMessage = new javax.swing.JLabel();
        LabelGenderMessage = new javax.swing.JLabel();
        ButtonBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Flores Charizza Mae, Ibay Jimwell, Calara John Benedict,Dela Cruz Noel, Yambao Kazuya James, Ocampo Joseph");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        MainPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText(" Enter your admission information below");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel2.setText("COLLEGE ADMISSION FORM");

        LabelName.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        LabelName.setText("Name");

        TextFieldFirstName.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        LabelFirstName.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        LabelFirstName.setText(" First Name");

        TextFieldMiddleName.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        LabelMiddleName.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        LabelMiddleName.setText(" Middle Name");

        TextFieldLastName.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        LabelLastName.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        LabelLastName.setText(" Last Name");

        LabelBirthDate.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        LabelBirthDate.setText("Birth Date");

        ComboBoxDay.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        ComboBoxDay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Please select a day", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        ComboBoxMonth.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        ComboBoxMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Please select a month", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));

        ComboBoxYear.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        ComboBoxYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Please select a year", "1900", "1901", "1902", "1903", "1904", "1905", "1906", "1907", "1908", "1909", "1910", "1911", "1912", "1913", "1914", "1915", "1916", "1917", "1918", "1919", "1920", "1921", "1922", "1923", "1924", "1925", "1926", "1927", "1928", "1929", "1930", "1931", "1932", "1933", "1934", "1935", "1936", "1937", "1938", "1939", "1940", "1941", "1942", "1943", "1944", "1945", "1946", "1947", "1948", "1949", "1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025" }));

        LabelYear.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        LabelYear.setText(" Year");

        LabelMonth.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        LabelMonth.setText(" Month");

        LabelDay.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        LabelDay.setText(" Day");

        LabelGender.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        LabelGender.setText("Gender");

        ButtonGroupGender.add(RadioButtonMale);
        RadioButtonMale.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        RadioButtonMale.setText("Male");

        ButtonGroupGender.add(RadioButtonFemale);
        RadioButtonFemale.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        RadioButtonFemale.setText("Female");

        LabelGender1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        LabelGender1.setText("Contacts");

        TextFieldContactNumber.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        LabelContactNumber.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        LabelContactNumber.setText(" Contact Number");

        TextFieldEmailAddress.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        LabelEmailAddress.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        LabelEmailAddress.setText(" Email Address");

        LabelGender2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        LabelGender2.setText("Mailing Address");

        TextFieldStreetAddress.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        LabelStreetAddress.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        LabelStreetAddress.setText(" Street Address");

        LabelBarangay.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        LabelBarangay.setText(" Barangay");

        TextFieldBarangay.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        TextFieldCity.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        TextFieldProvince.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        LabelProvince.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        LabelProvince.setText(" Province");

        LabelCity.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        LabelCity.setText(" City");

        TextFieldZipCode.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        LabelZipCode.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        LabelZipCode.setText("Zip Code");

        LabelCoursePreference.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        LabelCoursePreference.setText("Course Preference");

        jCheckBox1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jCheckBox1.setText("Computer Science");

        jCheckBox2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jCheckBox2.setText("Business Administration");

        jCheckBox3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jCheckBox3.setText("Mechanical Engineering");

        jCheckBox4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jCheckBox4.setText("Electrical Engineering");

        jCheckBox5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jCheckBox5.setText("Civil Engineering");

        jCheckBox6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jCheckBox6.setText("Medicine");

        jCheckBox7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jCheckBox7.setText("Law");

        jCheckBox8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jCheckBox8.setText("Psychology");

        jCheckBox9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jCheckBox9.setText("Arts and Humanities");

        jCheckBox10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jCheckBox10.setText("Biotechnology");

        ButtonSubmit.setBackground(new java.awt.Color(37, 99, 235));
        ButtonSubmit.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        ButtonSubmit.setForeground(new java.awt.Color(249, 250, 251));
        ButtonSubmit.setText("Submit");
        ButtonSubmit.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        ButtonSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSubmitActionPerformed(evt);
            }
        });

        LabelCoursePreferenceMessage.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        LabelGenderMessage.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        ButtonBack.setBackground(new java.awt.Color(209, 213, 219));
        ButtonBack.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        ButtonBack.setForeground(new java.awt.Color(3, 7, 18));
        ButtonBack.setText("Back");
        ButtonBack.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        ButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(132, Short.MAX_VALUE))
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelName)
                            .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(MainPanelLayout.createSequentialGroup()
                                    .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(LabelFirstName)
                                        .addComponent(LabelMonth)
                                        .addComponent(TextFieldFirstName))
                                    .addGap(2, 2, 2)
                                    .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(MainPanelLayout.createSequentialGroup()
                                            .addGap(4, 4, 4)
                                            .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(TextFieldMiddleName, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(LabelMiddleName)))
                                        .addGroup(MainPanelLayout.createSequentialGroup()
                                            .addGap(6, 6, 6)
                                            .addComponent(LabelDay)))
                                    .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(MainPanelLayout.createSequentialGroup()
                                            .addGap(3, 3, 3)
                                            .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(TextFieldLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(LabelLastName)))
                                        .addGroup(MainPanelLayout.createSequentialGroup()
                                            .addGap(8, 8, 8)
                                            .addComponent(LabelYear))))
                                .addGroup(MainPanelLayout.createSequentialGroup()
                                    .addComponent(LabelBirthDate)
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                                    .addComponent(ComboBoxMonth, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ComboBoxDay, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ComboBoxYear, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(37, 37, 37))
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addComponent(LabelGender)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LabelGender1)
                        .addGap(390, 390, 390))
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RadioButtonFemale)
                            .addComponent(RadioButtonMale))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextFieldContactNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelContactNumber))
                        .addGap(3, 3, 3)
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextFieldEmailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelEmailAddress))
                        .addGap(40, 40, 40))
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelGender2)
                            .addGroup(MainPanelLayout.createSequentialGroup()
                                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TextFieldStreetAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LabelStreetAddress))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelBarangay)
                                    .addComponent(TextFieldBarangay, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(LabelCoursePreference))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jCheckBox1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCheckBox2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCheckBox3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCheckBox4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCheckBox5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jCheckBox6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCheckBox7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCheckBox8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCheckBox9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCheckBox10, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(170, 170, 170))
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MainPanelLayout.createSequentialGroup()
                                .addComponent(LabelCoursePreferenceMessage)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(ButtonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtonSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelGenderMessage)
                            .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(LabelZipCode)
                                .addComponent(TextFieldZipCode)
                                .addGroup(MainPanelLayout.createSequentialGroup()
                                    .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(TextFieldCity, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(LabelCity))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(LabelProvince)
                                        .addComponent(TextFieldProvince, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(LabelName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addComponent(TextFieldFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LabelFirstName))
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addComponent(TextFieldMiddleName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LabelMiddleName))
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addComponent(TextFieldLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LabelLastName)))
                .addGap(27, 27, 27)
                .addComponent(LabelBirthDate)
                .addGap(8, 8, 8)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboBoxMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBoxDay, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBoxYear, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LabelMonth)
                        .addComponent(LabelDay))
                    .addComponent(LabelYear))
                .addGap(18, 18, 18)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelGender)
                            .addComponent(LabelGender1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(RadioButtonMale)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(RadioButtonFemale))
                    .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(MainPanelLayout.createSequentialGroup()
                            .addComponent(TextFieldContactNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(LabelContactNumber))
                        .addGroup(MainPanelLayout.createSequentialGroup()
                            .addComponent(TextFieldEmailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(LabelEmailAddress))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabelGenderMessage)
                .addGap(26, 26, 26)
                .addComponent(LabelGender2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldStreetAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextFieldBarangay, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelStreetAddress)
                    .addComponent(LabelBarangay))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldCity, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextFieldProvince, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelCity)
                    .addComponent(LabelProvince))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TextFieldZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelZipCode)
                .addGap(26, 26, 26)
                .addComponent(LabelCoursePreference)
                .addGap(17, 17, 17)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addComponent(jCheckBox1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox5))
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addComponent(jCheckBox6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox10)))
                .addGap(18, 18, 18)
                .addComponent(LabelCoursePreferenceMessage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     void ValidationMessage(String message, JLabel label) {
         label.setForeground(Color.RED);
         label.setText("* " + message);
     }
     
     void ValidationMessage(String text, JLabel label, boolean isValid) {
         label.setForeground(Color.BLACK);
         label.setText(" " + text);
     }
     
    private void ButtonSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSubmitActionPerformed
        
        boolean isFormValid = true;
        
        if (TextFieldFirstName.getText().trim().isEmpty()) {
            ValidationMessage("First Name is required.", LabelFirstName);
            isFormValid = false;
        } else {
            ValidationMessage("First Name", LabelFirstName, true);
        }
        
        if (TextFieldLastName.getText().trim().isEmpty()) {
            ValidationMessage("Last Name is required.", LabelLastName);
            isFormValid = false;
        } else {
            ValidationMessage("Last Name", LabelLastName, true);
        }
        
        if(ComboBoxDay.getSelectedIndex() == 0) {
            ValidationMessage("Day is required.", LabelDay);
            isFormValid = false;
        } else {
            ValidationMessage("Day", LabelDay, true);
        }
        
        if(ComboBoxMonth.getSelectedIndex() == 0) {
            ValidationMessage("Month is required.", LabelMonth);
            isFormValid = false;
        } else {
            ValidationMessage("Month", LabelMonth, true);
        }
        
         if(ComboBoxYear.getSelectedIndex() == 0) {
            ValidationMessage("Year is required.", LabelYear);
            isFormValid = false;
        } else {
              ValidationMessage("Year", LabelYear, true);
         }
         
        if (!RadioButtonFemale.isSelected() && !RadioButtonMale.isSelected()) {
             ValidationMessage("Gender is required.", LabelGenderMessage);
             isFormValid = false;
        } else {
            ValidationMessage("", LabelGenderMessage, true);
        }
        
        if (TextFieldContactNumber.getText().trim().isEmpty()) {
            ValidationMessage("Contact Number is required.", LabelContactNumber);
            isFormValid = false;
        } else if (!TextFieldContactNumber.getText().matches("\\d+")) {
            ValidationMessage("Contact Number must be digits.", LabelContactNumber);
            isFormValid = false;
        } else if (!(TextFieldContactNumber.getText().length() == 11)) {
            ValidationMessage("Contact Number must be 11 digits.", LabelContactNumber);
            isFormValid = false;
        } else if (!TextFieldContactNumber.getText().startsWith("09")) {
            ValidationMessage("Contact Number must starts with 09.", LabelContactNumber);
            isFormValid = false;
        } else {
            ValidationMessage("Contact Number", LabelContactNumber, true);
        }
         
        if (TextFieldEmailAddress.getText().trim().isEmpty()) {
            ValidationMessage("Email Address is required.", LabelEmailAddress);
            isFormValid = false;
        } else if (!TextFieldEmailAddress.getText().matches("^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+$")) {
            ValidationMessage("Email Address is invalid.", LabelEmailAddress);
        } else {
           ValidationMessage("Email Address", LabelEmailAddress, true);
        }
        
        if (TextFieldStreetAddress.getText().trim().isEmpty()) {
            ValidationMessage("Street Address is required.", LabelStreetAddress);
            isFormValid = false;
        } else {
            ValidationMessage("Street Address", LabelStreetAddress, true);
        }
        
        if (TextFieldBarangay.getText().trim().isEmpty()) {
            ValidationMessage("Barangay is required.", LabelBarangay);
            isFormValid = false;
        } else {
            ValidationMessage("Barangay", LabelBarangay, true);
        }
        
        if (TextFieldCity.getText().trim().isEmpty()) {
            ValidationMessage("City is required.", LabelCity);
            isFormValid = false;
        } else {
            ValidationMessage("City", LabelCity, true);
        }
        
        if (TextFieldProvince.getText().trim().isEmpty()) {
            ValidationMessage("Province is required.", LabelProvince);
            isFormValid = false;
        } else {
            ValidationMessage("Province", LabelProvince, true);
        }
        
        if (TextFieldZipCode.getText().trim().isEmpty()) {
            ValidationMessage("Zip Code is required.", LabelZipCode);
            isFormValid = false;
        } else if (!TextFieldZipCode.getText().matches("\\d+")) {
             ValidationMessage("Zip Code must be digits", LabelZipCode);
             isFormValid = false;
        } else {
            ValidationMessage("Zip Code", LabelZipCode, true);
        }
        
        if (!(
            jCheckBox1.isSelected() ||
            jCheckBox2.isSelected() ||
            jCheckBox3.isSelected() ||
            jCheckBox4.isSelected() ||
            jCheckBox5.isSelected() ||
            jCheckBox6.isSelected() ||
            jCheckBox7.isSelected() ||
            jCheckBox8.isSelected() ||
            jCheckBox9.isSelected() ||
            jCheckBox10.isSelected()
           )) {
            ValidationMessage("Course Preference is required.", LabelCoursePreferenceMessage);
            isFormValid = false;
        } else {
            ValidationMessage("", LabelCoursePreferenceMessage, true);
        }
        
//                 TextFieldFirstName.setText("");
//                 TextFieldMiddleName.setText("");
//                 TextFieldLastName.setText("");
//                 ComboBoxMonth.setSelectedIndex(0);
//                 ComboBoxDay.setSelectedIndex(0);
//                 ComboBoxYear.setSelectedIndex(0);
//                 RadioButtonMale.setSelected(false);
//                 RadioButtonFemale.setSelected(false);
//                 TextFieldContactNumber.setText("");
//                 TextFieldEmailAddress.setText("");
//                 TextFieldStreetAddress.setText("");
//                 TextFieldBarangay.setText("");
//                 TextFieldCity.setText("");
//                 TextFieldProvince.setText("");
//                 TextFieldZipCode.setText("");
//                 jCheckBox1.setSelected(false);
//                 jCheckBox2.setSelected(false);
//                 jCheckBox3.setSelected(false); 
//                 jCheckBox4.setSelected(false);
//                 jCheckBox5.setSelected(false);
//                 jCheckBox6.setSelected(false);
//                 jCheckBox7.setSelected(false);
//                 jCheckBox8.setSelected(false);
//                 jCheckBox9.setSelected(false);
//                 jCheckBox10.setSelected(false);
        
        if (isFormValid) {
            
            Student student = new Student();
            student.first_name = TextFieldFirstName.getText();
            student.middle_name = TextFieldMiddleName.getText();
            student.last_name = TextFieldLastName.getText();
            student.birthday_month = ComboBoxMonth.getItemAt(ComboBoxMonth.getSelectedIndex());
            student.birthday_day = ComboBoxDay.getItemAt(ComboBoxDay.getSelectedIndex());
            student.birthday_year = ComboBoxYear.getItemAt(ComboBoxYear.getSelectedIndex());
            if (RadioButtonMale.isSelected()) {
                student.gender = "Male";
            } else {
                student.gender = "Female";
            }
            student.contact_number = TextFieldContactNumber.getText();
            student.email_address = TextFieldEmailAddress.getText();
            student.street_address = TextFieldStreetAddress.getText();
            student.barangay = TextFieldBarangay.getText();
            student.city = TextFieldCity.getText();
            student.province = TextFieldProvince.getText();
            student.zip_code = TextFieldZipCode.getText();
            JCheckBox[] coursesCheckbox = {
                    jCheckBox1,
                    jCheckBox2,
                    jCheckBox3,
                    jCheckBox4,
                    jCheckBox5,
                    jCheckBox6,
                    jCheckBox7,
                    jCheckBox8,
                    jCheckBox9,
                    jCheckBox10,
            };
            for (JCheckBox checkbox : coursesCheckbox) {
                if (checkbox.isSelected()) {
                    student.course_preference.add(checkbox.getText());
                }
            }
            
            Database database = new Database();
             
             if (isForUpdate) {
                int choices = JOptionPane.showConfirmDialog(this, "Are you sure you want to update record?", "Confirmation", JOptionPane.YES_NO_OPTION);
                if (choices == JOptionPane.YES_OPTION) {
                   database.Update(_id, student);
                   this.dispose();
                } 
             } else {
                int choices = JOptionPane.showConfirmDialog(this, "Are you sure you want to save record?", "Confirmation", JOptionPane.YES_NO_OPTION);
                if (choices == JOptionPane.YES_OPTION) {
                   database.Create(student);
                   this.dispose();
                } 
             }
        }
        
    }//GEN-LAST:event_ButtonSubmitActionPerformed

    private void ButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBackActionPerformed
        Main main = new Main();
        main.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ButtonBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonBack;
    public javax.swing.ButtonGroup ButtonGroupGender;
    private javax.swing.JButton ButtonSubmit;
    public javax.swing.JComboBox<String> ComboBoxDay;
    public javax.swing.JComboBox<String> ComboBoxMonth;
    public javax.swing.JComboBox<String> ComboBoxYear;
    public javax.swing.JLabel LabelBarangay;
    public javax.swing.JLabel LabelBirthDate;
    public javax.swing.JLabel LabelCity;
    public javax.swing.JLabel LabelContactNumber;
    public javax.swing.JLabel LabelCoursePreference;
    private javax.swing.JLabel LabelCoursePreferenceMessage;
    public javax.swing.JLabel LabelDay;
    public javax.swing.JLabel LabelEmailAddress;
    public javax.swing.JLabel LabelFirstName;
    public javax.swing.JLabel LabelGender;
    public javax.swing.JLabel LabelGender1;
    public javax.swing.JLabel LabelGender2;
    private javax.swing.JLabel LabelGenderMessage;
    public javax.swing.JLabel LabelLastName;
    public javax.swing.JLabel LabelMiddleName;
    public javax.swing.JLabel LabelMonth;
    public javax.swing.JLabel LabelName;
    public javax.swing.JLabel LabelProvince;
    public javax.swing.JLabel LabelStreetAddress;
    public javax.swing.JLabel LabelYear;
    public javax.swing.JLabel LabelZipCode;
    private javax.swing.JPanel MainPanel;
    public javax.swing.JRadioButton RadioButtonFemale;
    public javax.swing.JRadioButton RadioButtonMale;
    public javax.swing.JTextField TextFieldBarangay;
    public javax.swing.JTextField TextFieldCity;
    public javax.swing.JTextField TextFieldContactNumber;
    public javax.swing.JTextField TextFieldEmailAddress;
    public javax.swing.JTextField TextFieldFirstName;
    public javax.swing.JTextField TextFieldLastName;
    public javax.swing.JTextField TextFieldMiddleName;
    public javax.swing.JTextField TextFieldProvince;
    public javax.swing.JTextField TextFieldStreetAddress;
    public javax.swing.JTextField TextFieldZipCode;
    public javax.swing.JCheckBox jCheckBox1;
    public javax.swing.JCheckBox jCheckBox10;
    public javax.swing.JCheckBox jCheckBox2;
    public javax.swing.JCheckBox jCheckBox3;
    public javax.swing.JCheckBox jCheckBox4;
    public javax.swing.JCheckBox jCheckBox5;
    public javax.swing.JCheckBox jCheckBox6;
    public javax.swing.JCheckBox jCheckBox7;
    public javax.swing.JCheckBox jCheckBox8;
    public javax.swing.JCheckBox jCheckBox9;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

}
